package stochastacy.examples.eas

import stochastacy.aws.dynamodb.DynamoDbReadTarget
import stochastacy.aws.dynamodb.client.{JitterStrategy, SdkRetryStrategy}
import stochastacy.aws.dynamodb.table.ReadConsistency
import stochastacy.workload.*

import scala.concurrent.duration.*

/**
 * Top-level configuration for a single EAS burst-scenario simulation run.
 *
 * Wraps the two per-table component configs and owns the workload builder methods,
 * following the pattern of `ThermostatFleetScenarioConfig.toWorkloadDefinition`.
 *
 * @param scenarioId       Identifier written into every exported record.
 * @param burstMultiplier  Peak-rate multiplier for A1 polling: min=400 req/tick, peak=400×M.
 *                         At M≈7.6 the GSI partition (3000 RCU/s limit) is near saturation.
 * @param simulationTicks  Total simulation ticks (1 tick = 1 second). Default 1200 (20 min).
 * @param alertsConfig     Config for the `alerts` table and its `UseCaseSampler`.
 * @param uasConfig        Config for the `user-alert-status` table and its `UseCaseSampler`.
 */
case class EasScenarioConfig(
  scenarioId:      String                   = "eas-burst",
  burstMultiplier: Double                   = 7.6,
  simulationTicks: Long                     = 1200L,
  alertsConfig:    EasAlertsConfig          = EasAlertsConfig(),
  uasConfig:       EasUserAlertStatusConfig = EasUserAlertStatusConfig()
):
  require(burstMultiplier > 0.0, "burstMultiplier must be positive")
  require(simulationTicks > 0L,  "simulationTicks must be positive")
  require(scenarioId.nonEmpty,   "scenarioId must be non-empty")

  /**
   * SDK retry policy applied by `SdkClientStage` on the alerts table.
   *
   * Deliberately configured with a **1-second base backoff** rather than the true AWS
   * Java SDK v2 default of 100ms.  Rationale: the simulator's tick granularity is 1s,
   * so a 100ms base backoff would round all retry attempts into the same bucket
   * (failure-tick + 1).  A 1s base with no jitter reproduces the previous demo's
   * three-attempt chained-Retry pattern with exponential backoff of 1, 2, 4 ticks —
   * exactly the retry tail shape the pre-Slice-D demo displayed via chained
   * `FlowDefinition.Retry` entries with `lagTicks = 1, 2, 4`.
   *
   * Future work: switching to sub-second tick resolution (e.g., `tickDurationSeconds =
   * 0.1`) would let this use the true SDK-standard `baseBackoff = 100.millis` and
   * still spread across multiple ticks.  That refactor also requires re-calibrating
   * the workload's Poisson rates and sinusoid periods for the finer tick grain.
   */
  val sdkRetryStrategy: SdkRetryStrategy = SdkRetryStrategy(
    maxAttempts     = 3,
    baseBackoff     = 1.second,
    maxBackoff      = 20.seconds,
    jitter          = JitterStrategy.None,
    retryProportion = 1.0
  )

  /**
   * Alerts-table workload:
   *   - A1 baseline:  Poisson(sinusoid(400, 400×M, 900, 450)) Query on GSI by-region-index
   *   - A3 write:     Poisson(0.2 in [295,305], else 0) PutItem with constant 4500-byte items
   *   - A2 follow-on: FollowOn of a1-poll on success, proportion=0.70, lag=1, GetItem
   *
   * Retries are NOT in the workload definition — they are generated by `SdkClientStage`
   * (see `sdkRetryStrategy` above), which observes throttled responses from the alerts
   * table and injects new attempts into the request stream with `clientAttempt` incremented.
   * Retried requests preserve `flowId = "a1-poll"` and differ only in `clientAttempt`.
   */
  def toAlertsWorkload: WorkloadDefinition =
    WorkloadDefinition(
      tableName = "alerts",
      usecase   = "alerts",
      flows = Vector(
        FlowDefinition.Independent(
          id   = "a1-poll",
          factory = PacedRequestFactory(
            rate  = PoissonSampler(
              TemporalShapeFunctions.sinusoid(400.0, 400.0 * burstMultiplier, 900L, 450L)
            ),
            factory = RequestShape.Query(
              target          = DynamoDbReadTarget.GlobalSecondaryIndex("alerts", "by-region-index"),
              readConsistency = ReadConsistency.EventuallyConsistent
            )
          )
        ),
        FlowDefinition.Independent(
          id   = "a3-write",
          factory = PacedRequestFactory(
            rate  = PoissonSampler(tick => if tick >= 295L && tick <= 305L then 0.2 else 0.0),
            factory = RequestShape.PutItem(ConstantSampler(4500L))
          )
        ),
        FlowDefinition.FollowOn(
          id           = "a2-fetch",
          sourceId     = "alerts",
          sourceFlowId = "a1-poll",
          outcome      = OutcomeFilter.Success,
          proportion   = 0.70,
          lagTicks     = 1,
          shape        = RequestShape.GetItem
        )
      )
    )

  /**
   * User-alert-status workload (open-loop, all independent):
   *   - S1 delivered:    triangular burst peaking at ~8333 req/tick at tick 320
   *   - S2 opened:       sinusoid(28, 833, 900, 480)
   *   - S3 acknowledged: sinusoid(17, 500, 900, 520)
   *
   * Item bytes sampled uniformly in [uasConfig.itemMinBytes, uasConfig.itemMaxBytes].
   */
  def toUasWorkload: WorkloadDefinition =
    val itemBytesSampler: StatelessSampler[Long] =
      Sampler.stateless((_, rng) =>
        uasConfig.itemMinBytes + rng.nextLong(uasConfig.itemMaxBytes - uasConfig.itemMinBytes + 1L)
      )
    WorkloadDefinition(
      tableName = "user-alert-status",
      usecase   = "user-alert-status",
      flows = Vector(
        FlowDefinition.Independent(
          id   = "s1-delivered",
          factory = PacedRequestFactory(
            rate  = PoissonSampler(tick =>
              math.max(0.0, TemporalShapeFunctions.triangularFactor(280L, 360L, 8334.0)(tick) - 1.0)
            ),
            factory = RequestShape.PutItem(itemBytesSampler)
          )
        ),
        FlowDefinition.Independent(
          id   = "s2-opened",
          factory = PacedRequestFactory(
            rate  = PoissonSampler(TemporalShapeFunctions.sinusoid(28.0, 833.0, 900L, 480L)),
            factory = RequestShape.UpdateItem(itemBytesSampler)
          )
        ),
        FlowDefinition.Independent(
          id   = "s3-acknowledged",
          factory = PacedRequestFactory(
            rate  = PoissonSampler(TemporalShapeFunctions.sinusoid(17.0, 500.0, 900L, 520L)),
            factory = RequestShape.UpdateItem(itemBytesSampler)
          )
        )
      )
    )

object EasScenarioConfig:
  val default: EasScenarioConfig = EasScenarioConfig()
  val BaseSeed: Long = 0x4541532d42555253L  // "EAS-BURS" in ASCII
