apiVersion: 1

datasources:
  - name: Stochastacy Postgres
    uid: stochastacy-postgres
    type: postgres
    access: proxy
    isDefault: true
    url: postgres:5432
    user: stochastacy
    secureJsonData:
      password: stochastacy
    jsonData:
      database: stochastacy_demo
      postgresVersion: 1600
      sslmode: disable
      timescaledb: false
