package stochastacy.aws.dynamodb

import stochastacy.aws.dynamodb.table.ReadConsistency
import stochastacy.aws.{AWSServiceRequestEvent, AWSServiceResponseEvent}
import stochastacy.sim.SimTime

sealed trait DynamoDbReadTarget

object DynamoDbReadTarget:
  final case class Table(tableName: String) extends DynamoDbReadTarget
  final case class GlobalSecondaryIndex(tableName: String, indexName: String) extends DynamoDbReadTarget
  final case class LocalSecondaryIndex(tableName: String, indexName: String) extends DynamoDbReadTarget

sealed trait DynamoDbOperationKind

object DynamoDbOperationKind:
  case object GetItem extends DynamoDbOperationKind
  case object PutItem extends DynamoDbOperationKind
  case object UpdateItem extends DynamoDbOperationKind
  case object DeleteItem extends DynamoDbOperationKind
  case object Query extends DynamoDbOperationKind
  case object Scan extends DynamoDbOperationKind
  case object PartiQLQuery extends DynamoDbOperationKind
  case object TransactWriteItems extends DynamoDbOperationKind
  case object TransactGetItems extends DynamoDbOperationKind

  def fromRequest(request: DynamoDBRequest): DynamoDbOperationKind =
    request match
      case _: GetItemRequest => GetItem
      case _: PutItemRequest => PutItem
      case _: UpdateItemRequest => UpdateItem
      case _: DeleteItemRequest => DeleteItem
      case _: QueryRequest => Query
      case _: ScanRequest => Scan
      case _: PartiQLQueryRequest => PartiQLQuery
      case _: TransactWriteItemsRequest => TransactWriteItems
      case _: TransactGetItemsRequest => TransactGetItems

sealed trait DynamoDbThroughputDimension

object DynamoDbThroughputDimension:
  case object Read extends DynamoDbThroughputDimension
  case object Write extends DynamoDbThroughputDimension

sealed trait DynamoDbThrottleReason

object DynamoDbThrottleReason:
  case object TableReadMaxOnDemandThroughputExceeded extends DynamoDbThrottleReason
  case object TableWriteMaxOnDemandThroughputExceeded extends DynamoDbThrottleReason
  case object GlobalSecondaryIndexReadMaxOnDemandThroughputExceeded extends DynamoDbThrottleReason
  case object GlobalSecondaryIndexWriteMaxOnDemandThroughputExceeded extends DynamoDbThrottleReason
  case object TableReadHotPartitionThroughputExceeded extends DynamoDbThrottleReason
  case object TableWriteHotPartitionThroughputExceeded extends DynamoDbThrottleReason
  case object GlobalSecondaryIndexReadHotPartitionThroughputExceeded extends DynamoDbThrottleReason
  case object GlobalSecondaryIndexWriteHotPartitionThroughputExceeded extends DynamoDbThrottleReason
  case object TableReadProvisionedThroughputExceeded extends DynamoDbThrottleReason
  case object TableWriteProvisionedThroughputExceeded extends DynamoDbThrottleReason
  case object GlobalSecondaryIndexReadProvisionedThroughputExceeded extends DynamoDbThrottleReason
  case object GlobalSecondaryIndexWriteProvisionedThroughputExceeded extends DynamoDbThrottleReason
  case object ReplicatedWriteCapacityExceeded extends DynamoDbThrottleReason

sealed trait DynamoDBRequest extends AWSServiceRequestEvent:
  /** Workload flow id that produced this request. Set by WorkloadRequestStream /
   *  FollowOnTransformerStage so that response events can be attributed back to
   *  the originating flow for derived-flow (follow-on / retry) rate computation.
   *  None for requests produced outside the workload system. */
  def flowId: Option[String]

  /** SDK-client retry attempt number.  0 for the initial request (the default);
   *  1, 2, ... for retries generated by an `SdkClientStage`.  Preserved unchanged
   *  from the original request's `flowId` — retries inherit the same `flowId`
   *  and only differ in `clientAttempt`. */
  def clientAttempt: Int

sealed trait DynamoDBResponse extends AWSServiceResponseEvent:
  /** Propagated from the originating request's flowId. Used by FollowOnTransformerStage
   *  to count outcomes per flow per tick. None when the originating request had no flowId. */
  def flowId: Option[String]

  /** Propagated from the originating request's `clientAttempt`.  Used by
   *  `SdkClientStage` to decide whether a retryable failure should trigger a
   *  next-attempt retry (bounded by the strategy's `maxAttempts`). */
  def clientAttempt: Int

sealed trait RequestedReadShape

object RequestedReadShape:
  case object AllProjectedOrFullItem extends RequestedReadShape
  final case class RequestedAttributeBytes(bytes: Long) extends RequestedReadShape:
    require(bytes > 0L, s"RequestedAttributeBytes.bytes must be positive, got $bytes")
  case object ProjectedOnly extends RequestedReadShape

case class GetItemRequest(
  override val eventTime: SimTime,
  override val usecase:   Any,
  override val intraTick: Double         = 0.0,
  flowId:                 Option[String] = None,
  clientAttempt:          Int            = 0
) extends DynamoDBRequest

case class PutItemRequest(
  override val eventTime: SimTime,
  override val usecase:   Any,
  itemBytes:              Long,
  override val intraTick: Double         = 0.0,
  flowId:                 Option[String] = None,
  clientAttempt:          Int            = 0
) extends DynamoDBRequest

case class UpdateItemRequest(
  override val eventTime: SimTime,
  override val usecase:   Any,
  itemBytes:              Long,
  override val intraTick: Double         = 0.0,
  flowId:                 Option[String] = None,
  clientAttempt:          Int            = 0
) extends DynamoDBRequest

case class DeleteItemRequest(
  override val eventTime: SimTime,
  override val usecase:   Any,
  override val intraTick: Double         = 0.0,
  flowId:                 Option[String] = None,
  clientAttempt:          Int            = 0
) extends DynamoDBRequest

case class QueryRequest(
  override val eventTime: SimTime,
  override val usecase:   Any,
  target:                 DynamoDbReadTarget,
  readConsistency:        ReadConsistency    = ReadConsistency.EventuallyConsistent,
  requestedReadShape:     RequestedReadShape = RequestedReadShape.AllProjectedOrFullItem,
  override val intraTick: Double             = 0.0,
  flowId:                 Option[String]     = None,
  clientAttempt:          Int                = 0
) extends DynamoDBRequest

case class ScanRequest(
  override val eventTime: SimTime,
  override val usecase:   Any,
  target:                 DynamoDbReadTarget,
  readConsistency:        ReadConsistency    = ReadConsistency.EventuallyConsistent,
  requestedReadShape:     RequestedReadShape = RequestedReadShape.AllProjectedOrFullItem,
  override val intraTick: Double             = 0.0,
  flowId:                 Option[String]     = None,
  clientAttempt:          Int                = 0
) extends DynamoDBRequest

case class PartiQLQueryRequest(
  override val eventTime: SimTime,
  override val usecase:   Any,
  queryText:              String,
  override val intraTick: Double         = 0.0,
  flowId:                 Option[String] = None,
  clientAttempt:          Int            = 0
) extends DynamoDBRequest

/**
 * The non-error response to a GetItem request submitted to a DDB table
 */
case class GetItemResponse(
  override val eventTime: SimTime,
  override val usecase:   Any,
  itemFound:              Boolean,
  itemBytes:              Option[Long],
  override val intraTick: Double         = 0.0,
  flowId:                 Option[String] = None,
  clientAttempt:          Int            = 0
) extends DynamoDBResponse

case class PutItemResponse(
  override val eventTime: SimTime,
  override val usecase:   Any,
  storedItemBytes:        Long,
  createdNewItem:         Boolean,
  previousItemBytes:      Option[Long],
  override val intraTick: Double         = 0.0,
  flowId:                 Option[String] = None,
  clientAttempt:          Int            = 0
) extends DynamoDBResponse

case class UpdateItemResponse(
  override val eventTime: SimTime,
  override val usecase:   Any,
  storedItemBytes:        Long,
  createdNewItem:         Boolean,
  previousItemBytes:      Option[Long],
  override val intraTick: Double         = 0.0,
  flowId:                 Option[String] = None,
  clientAttempt:          Int            = 0
) extends DynamoDBResponse

case class DeleteItemResponse(
  override val eventTime: SimTime,
  override val usecase:   Any,
  deletedItemBytes:       Option[Long],
  override val intraTick: Double         = 0.0,
  flowId:                 Option[String] = None,
  clientAttempt:          Int            = 0
) extends DynamoDBResponse

case class QueryResponse(
  override val eventTime: SimTime,
  override val usecase:   Any,
  target:                 DynamoDbReadTarget,
  readConsistency:        ReadConsistency,
  evaluatedItemCount:     Long,
  evaluatedBytes:         Long,
  returnedItemCount:      Long,
  returnedBytes:          Long,
  override val intraTick: Double         = 0.0,
  flowId:                 Option[String] = None,
  clientAttempt:          Int            = 0
) extends DynamoDBResponse

case class ScanResponse(
  override val eventTime: SimTime,
  override val usecase:   Any,
  target:                 DynamoDbReadTarget,
  readConsistency:        ReadConsistency,
  evaluatedItemCount:     Long,
  evaluatedBytes:         Long,
  returnedItemCount:      Long,
  returnedBytes:          Long,
  override val intraTick: Double         = 0.0,
  flowId:                 Option[String] = None,
  clientAttempt:          Int            = 0
) extends DynamoDBResponse

case class PartiQLQueryResponse(
  override val eventTime: SimTime,
  override val usecase:   Any,
  queryText:              String,
  override val intraTick: Double         = 0.0,
  flowId:                 Option[String] = None,
  clientAttempt:          Int            = 0
) extends DynamoDBResponse

case class ThrottledResponse(
  override val eventTime: SimTime,
  override val usecase:   Any,
  operation:              DynamoDbOperationKind,
  target:                 stochastacy.aws.dynamodb.table.DynamoDbTarget,
  dimension:              DynamoDbThroughputDimension,
  reason:                 DynamoDbThrottleReason,
  override val intraTick: Double         = 0.0,
  flowId:                 Option[String] = None,
  clientAttempt:          Int            = 0
) extends DynamoDBResponse

/**
 * Emitted when an admitted write would push an LSI-backed item collection past the
 * configured `itemCollectionSizeLimitBytes`. Distinct from `ThrottledResponse`:
 * this is a storage-rule validation failure, not a throughput-throttling outcome.
 *
 * Real DynamoDB raises `ItemCollectionSizeLimitExceededException` separately from
 * `ProvisionedThroughputExceededException`; the simulator preserves that distinction.
 */
case class ItemCollectionSizeLimitExceededResponse(
  override val eventTime:    SimTime,
  override val usecase:      Any,
  operation:                 DynamoDbOperationKind,
  target:                    stochastacy.aws.dynamodb.table.DynamoDbTarget,
  resultingCollectionBytes:  Long,
  limitBytes:                Long,
  override val intraTick:    Double         = 0.0,
  flowId:                    Option[String] = None,
  clientAttempt:             Int            = 0
) extends DynamoDBResponse

/**
 * Emitted when the storage layer simulates a transient internal error for an otherwise
 * admitted request. Parallels real DynamoDB's `InternalServerError`. No capacity is
 * consumed and no state is mutated. Rate is controlled by `DynamoDbTable.Config.systemErrorRate`.
 */
final case class SystemErrorResponse(
  override val eventTime: SimTime,
  override val usecase:   Any,
  operation:              DynamoDbOperationKind,
  target:                 stochastacy.aws.dynamodb.table.DynamoDbTarget,
  override val intraTick: Double         = 0.0,
  flowId:                 Option[String] = None,
  clientAttempt:          Int            = 0
) extends DynamoDBResponse

/**
 * Emitted when a management-API reconfiguration event is rejected. The simulator enforces
 * real DynamoDB constraints (e.g., the 24-hour billing mode switch cooldown) and emits this
 * response instead of applying the change when the constraint is violated.
 */
final case class ReconfigurationRejectedResponse(
  override val eventTime: SimTime,
  override val usecase:   Any,
  reason:                 String,
  override val intraTick: Double         = 0.0,
  flowId:                 Option[String] = None,
  clientAttempt:          Int            = 0
) extends DynamoDBResponse

/**
 * A transactional write containing multiple sub-item writes (puts/updates). All items are
 * admitted all-or-nothing. Total WCU cost is 2× per item (DynamoDB transaction pricing).
 */
case class TransactWriteItemsRequest(
  override val eventTime: SimTime,
  override val usecase:   Any,
  perItemBytes:           Vector[Long],
  override val intraTick: Double         = 0.0,
  flowId:                 Option[String] = None,
  clientAttempt:          Int            = 0
) extends DynamoDBRequest:
  require(perItemBytes.nonEmpty, "TransactWriteItemsRequest.perItemBytes must be non-empty")
  require(perItemBytes.forall(_ >= 0L), "TransactWriteItemsRequest.perItemBytes values must be non-negative")

/**
 * A transactional read containing multiple sub-item gets. All reads are strongly consistent
 * (DynamoDB requirement). Total RCU cost is 2× per item.
 */
case class TransactGetItemsRequest(
  override val eventTime: SimTime,
  override val usecase:   Any,
  itemCount:              Int,
  override val intraTick: Double         = 0.0,
  flowId:                 Option[String] = None,
  clientAttempt:          Int            = 0
) extends DynamoDBRequest:
  require(itemCount > 0, s"TransactGetItemsRequest.itemCount must be positive, got $itemCount")

case class TransactWriteItemsResponse(
  override val eventTime: SimTime,
  override val usecase:   Any,
  itemCount:              Int,
  override val intraTick: Double         = 0.0,
  flowId:                 Option[String] = None,
  clientAttempt:          Int            = 0
) extends DynamoDBResponse

case class TransactGetItemsResponse(
  override val eventTime: SimTime,
  override val usecase:   Any,
  items:                  Vector[Option[Long]],
  override val intraTick: Double         = 0.0,
  flowId:                 Option[String] = None,
  clientAttempt:          Int            = 0
) extends DynamoDBResponse:
  require(items.nonEmpty, "TransactGetItemsResponse.items must be non-empty")
